//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trixter.XDream.API.Testing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Trixter.XDream.API.Testing.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] buttons {
            get {
                object obj = ResourceManager.GetObject("buttons", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] crank_speed {
            get {
                object obj = ResourceManager.GetObject("crank_speed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] flywheel_crank_messages {
            get {
                object obj = ResourceManager.GetObject("flywheel_crank_messages", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] flywheel_spindown_messages {
            get {
                object obj = ResourceManager.GetObject("flywheel_spindown_messages", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] flywheel_spindown_messages_R000 {
            get {
                object obj = ResourceManager.GetObject("flywheel_spindown_messages_R000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] flywheel_spindown_messages_R010 {
            get {
                object obj = ResourceManager.GetObject("flywheel_spindown_messages_R010", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] flywheel_spindown_messages_R020 {
            get {
                object obj = ResourceManager.GetObject("flywheel_spindown_messages_R020", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] flywheel_spindown_messages_R030 {
            get {
                object obj = ResourceManager.GetObject("flywheel_spindown_messages_R030", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] flywheel_spindown_messages_R040 {
            get {
                object obj = ResourceManager.GetObject("flywheel_spindown_messages_R040", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] flywheel_spindown_messages_R050 {
            get {
                object obj = ResourceManager.GetObject("flywheel_spindown_messages_R050", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] flywheel_spindown_messages_R060 {
            get {
                object obj = ResourceManager.GetObject("flywheel_spindown_messages_R060", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] flywheel_spindown_messages_R070 {
            get {
                object obj = ResourceManager.GetObject("flywheel_spindown_messages_R070", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] flywheel_spindown_messages_R080 {
            get {
                object obj = ResourceManager.GetObject("flywheel_spindown_messages_R080", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] flywheel_spindown_messages_R090 {
            get {
                object obj = ResourceManager.GetObject("flywheel_spindown_messages_R090", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] flywheel_spindown_messages_R100 {
            get {
                object obj = ResourceManager.GetObject("flywheel_spindown_messages_R100", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] flywheel_spindown_messages_R110 {
            get {
                object obj = ResourceManager.GetObject("flywheel_spindown_messages_R110", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] flywheel_spindown_messages_R120 {
            get {
                object obj = ResourceManager.GetObject("flywheel_spindown_messages_R120", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] flywheel_spindown_messages_R130 {
            get {
                object obj = ResourceManager.GetObject("flywheel_spindown_messages_R130", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] flywheel_spindown_messages_R140 {
            get {
                object obj = ResourceManager.GetObject("flywheel_spindown_messages_R140", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] flywheel_spindown_messages_R150 {
            get {
                object obj = ResourceManager.GetObject("flywheel_spindown_messages_R150", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] flywheel_spindown_messages_R160 {
            get {
                object obj = ResourceManager.GetObject("flywheel_spindown_messages_R160", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] flywheel_spindown_messages_R170 {
            get {
                object obj = ResourceManager.GetObject("flywheel_spindown_messages_R170", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] flywheel_spindown_messages_R180 {
            get {
                object obj = ResourceManager.GetObject("flywheel_spindown_messages_R180", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] flywheel_spindown_messages_R190 {
            get {
                object obj = ResourceManager.GetObject("flywheel_spindown_messages_R190", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] flywheel_spindown_messages_R200 {
            get {
                object obj = ResourceManager.GetObject("flywheel_spindown_messages_R200", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] flywheel_spindown_messages_R210 {
            get {
                object obj = ResourceManager.GetObject("flywheel_spindown_messages_R210", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] flywheel_spindown_messages_R220 {
            get {
                object obj = ResourceManager.GetObject("flywheel_spindown_messages_R220", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] flywheel_spindown_messages_R230 {
            get {
                object obj = ResourceManager.GetObject("flywheel_spindown_messages_R230", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] flywheel_spindown_messages_R240 {
            get {
                object obj = ResourceManager.GetObject("flywheel_spindown_messages_R240", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] flywheel_spindown_messages_R250 {
            get {
                object obj = ResourceManager.GetObject("flywheel_spindown_messages_R250", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] heartrate {
            get {
                object obj = ResourceManager.GetObject("heartrate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] input {
            get {
                object obj = ResourceManager.GetObject("input", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
